void strt_scrn(){
  gotoxy(25, 0);
  printf("            .                  \n\n");
  gotoxy(25, 2);
  suspend(4);
  printf("         .     .               \n\n");
  gotoxy(25, 4);
  suspend(4);
  printf("      .           .            \n\n");
  gotoxy(25, 6);
  suspend(4);
  printf("    .    AhnTri      .   1.2.4 \n\n");
  gotoxy(25, 8);
  suspend(4);
  printf(" .   .   .    .   .    .       \n\n");
  gotoxy(25, 10);
  suspend(4);
  printf("System is starting...          \n\n");
  gotoxy(25, 12);
  printf("         ");
  print_char(176);
  suspend(1);
  print_char(177);
  suspend(1);
  print_char(178);
  suspend(1);
  print_char(219);
  suspend(1);
  print_char(178);
  suspend(1);
  print_char(177);
  suspend(1);
  print_char(176);
  gotoxy(25, 12);
  printf("         ");
  print_char(16);
  suspend(1);
  print_char(16);
  suspend(1);
  print_char(16);
  suspend(1);
  print_char(219);
  suspend(1);
  print_char(17);
  suspend(1);
  print_char(17);
  suspend(1);
  print_char(17);
  gotoxy(25, 12);
  printf("         ");
  print_char(176);
  suspend(1);
  print_char(177);
  suspend(1);
  print_char(178);
  suspend(1);
  print_char(219);
  suspend(1);
  print_char(178);
  suspend(1);
  print_char(177);
  suspend(1);
  print_char(176);
  gotoxy(25, 12);
  printf("         ");
  print_char(16);
  suspend(1);
  print_char(16);
  suspend(1);
  print_char(16);
  suspend(1);
  print_char(219);
  suspend(1);
  print_char(17);
  suspend(1);
  print_char(17);
  suspend(1);
  print_char(17);
  gotoxy(25, 12);
  printf("         ");
  print_char(176);
  suspend(1);
  print_char(177);
  suspend(1);
  print_char(178);
  suspend(1);
  print_char(219);
  suspend(1);
  print_char(178);
  suspend(1);
  print_char(177);
  suspend(1);
  print_char(176);
  gotoxy(25, 12);
  printf("         ");
  print_char(16);
  suspend(1);
  print_char(16);
  suspend(1);
  print_char(16);
  suspend(1);
  print_char(219);
  suspend(1);
  print_char(17);
  suspend(1);
  print_char(17);
  suspend(1);
  print_char(17);
  gotoxy(25, 12);
  printf("         ");
  print_char(176);
  suspend(1);
  print_char(177);
  suspend(1);
  print_char(178);
  suspend(1);
  print_char(219);
  suspend(1);
  print_char(178);
  suspend(1);
  print_char(177);
  suspend(1);
  print_char(176);
  gotoxy(25, 12);
  printf("         ");
  print_char(16);
  suspend(1);
  print_char(16);
  suspend(1);
  print_char(16);
  suspend(1);
  print_char(219);
  suspend(1);
  print_char(17);
  suspend(1);
  print_char(17);
  suspend(1);
  print_char(17);
}
