#include "../kernel.h"
#include "../init/api.h"

process art(){
	clscr();
	printf("                    AhnTri Sun\n\n");
	os_print_color("```````...................-.--.............```````", BROWN, BLACK);
	suspend(1);
	os_print_color("\n`````...........--------------------..........````", BROWN, BLACK);
	suspend(1);
	os_print_color("\n````.........--------------------------........```", BROWN, BLACK);
	suspend(1);
	os_print_color("\n``........---------------", BROWN, BLACK);
	suspend(1);
	os_print_color(":::::::::", YELLOW, BLACK);
	suspend(1);
	os_print_color("-------........`", BROWN, BLACK);
	suspend(1);
	os_print_color("\n`.......-------------", BROWN, BLACK);
	suspend(1);
	os_print_color(":::::::::::::::", YELLOW, BLACK);
	suspend(1);
	os_print_color("-----.........", BROWN, BLACK);
	suspend(1);
	os_print_color("\n........---------", BROWN, BLACK);
	suspend(1);
	os_print_color(":::::::::", YELLOW, BLACK);
	suspend(1);
	os_print_color("//", YELLOW, BLACK);
	suspend(1);
	os_print_color("::::::::::", YELLOW, BLACK);
	suspend(1);
	os_print_color("-----.......", BROWN, BLACK);
	suspend(1);
	os_print_color("\n......-------", BROWN, BLACK);
	suspend(1);
	os_print_color("::::://///++++ooooooo++++///:::", YELLOW, BLACK);
	suspend(1);
	os_print_color("---..", BROWN, BLACK);
	suspend(1);
	os_print_color("\n.........-------", BROWN, BLACK);
	suspend(1);
	os_print_color(":::////+++ooooooooooooo+++//:::", YELLOW, BLACK);
	suspend(1);
	os_print_color("---", BROWN, BLACK);
	suspend(1);
	os_print_color("\n......-------", BROWN, BLACK);
	suspend(1);
	os_print_color("::::::////+++oooooo++///::", YELLOW, BLACK);
	suspend(1);
	os_print_color("::----.....", BROWN, BLACK);
	suspend(1);
	os_print_color("\n``........--------", BROWN, BLACK);
	suspend(1);
	os_print_color("::::::////++++++++///:::", YELLOW, BLACK);
	suspend(1);
	os_print_color("---.....", BROWN, BLACK);
	suspend(1);
	os_print_color("\n```......--------", BROWN, BLACK);
	suspend(1);
	os_print_color("::::::////", YELLOW, BLACK);
	suspend(1);
	os_print_color("+++", RED, BLACK);
	suspend(1);
	os_print_color("ooo", WHITE, BLACK);
	suspend(1);
	os_print_color("++", RED, BLACK);
	suspend(1);
	os_print_color("///:::", YELLOW, BLACK);
	suspend(1);
	os_print_color("---......", BROWN, BLACK);
	suspend(1);
	os_print_color("\n````......----------", BROWN, BLACK);
	suspend(1);
	os_print_color("::://", YELLOW, BLACK);
	suspend(1);
	os_print_color("++", RED, BLACK);
	suspend(1);
	os_print_color("oooooooo", WHITE, BLACK);
	suspend(1);
	os_print_color("++", RED, BLACK);
	suspend(1);
	os_print_color("///:::", YELLOW, BLACK);
	suspend(1);
	os_print_color("---....", BROWN, BLACK);
	suspend(1);
	os_print_color("\n```````......--------", BROWN, BLACK);
	suspend(1);
	os_print_color("::/", YELLOW, BLACK);
	suspend(1);
	os_print_color("+", RED, BLACK);
	suspend(1);
	os_print_color("ooossssssooo", WHITE, BLACK);
	suspend(1);
	os_print_color("+", RED, BLACK);
	suspend(1);
	os_print_color("/::", YELLOW, BLACK);
	suspend(1);
	os_print_color("--......`", BROWN, BLACK);
	suspend(1);
	os_print_color("\n   ````````....-------", BROWN, BLACK);
	suspend(1);
	os_print_color("::/", YELLOW, BLACK);
	suspend(1);
	os_print_color("+", RED, BLACK);
	suspend(1);
	os_print_color("oosyyyyysso", WHITE, BLACK);
	suspend(1);
	os_print_color("++", RED, BLACK);
	suspend(1);
	os_print_color("/:", YELLOW, BLACK);
	suspend(1);
	os_print_color("--......``", BROWN, BLACK);
	suspend(1);
	os_print_color("\n   ````````....-------", BROWN, BLACK);
	suspend(1);
	os_print_color("::/", YELLOW, BLACK);
	suspend(1);
	os_print_color("+", RED, BLACK);
	suspend(1);
	os_print_color("oosyyyyysso", WHITE, BLACK);
	suspend(1);
	os_print_color("++", RED, BLACK);
	suspend(1);
	os_print_color("/:", YELLOW, BLACK);
	suspend(1);
	suspend(1);
	os_print_color("--......``", BROWN, BLACK);
	suspend(1);
	os_print_color("\n     ````````...-------", BROWN, BLACK);
	suspend(1);
	os_print_color(":/", YELLOW, BLACK);
	suspend(1);
	os_print_color("++", RED, BLACK);
	suspend(1);
	os_print_color("yhhhyyyys", WHITE, BLACK);
	suspend(1);
	os_print_color("++", RED, BLACK);
	suspend(1);
	os_print_color(":", YELLOW, BLACK);
	suspend(1);
	os_print_color("--......```", BROWN, BLACK);
	suspend(1);
	os_print_color("\n         ``````......---", BROWN, BLACK);
	suspend(1);
	os_print_color("::/", YELLOW, BLACK);
	suspend(1);
	os_print_color("+", RED, BLACK);
	suspend(1);
	os_print_color("hhhyyy", WHITE, BLACK);
	suspend(1);
	os_print_color("++", RED, BLACK);
	suspend(1);
	os_print_color("/:", YELLOW, BLACK);
	suspend(1);
	os_print_color(".......```", BROWN, BLACK);
	suspend(1);
	os_print_color("\n         ``````......-----", BROWN, BLACK);
	suspend(1);
	os_print_color(":/", YELLOW, BLACK);
	suspend(1);
	os_print_color("++", RED, BLACK);
	suspend(1);
	os_print_color("yyy", WHITE, BLACK);
	suspend(1);
	os_print_color("++", RED, BLACK);
	suspend(1);
	os_print_color("/:", YELLOW, BLACK);
	suspend(1);
	os_print_color(".......```", BROWN, BLACK);
	suspend(1);
	os_print_color("\n                 ````.......--", BROWN, BLACK);
	suspend(1);
	os_print_color(":", YELLOW, BLACK);
	suspend(1);
	os_print_color("---...``````       ", BROWN, BLACK);
	os_print_color("\n                     ```````.....````             ", BROWN, BLACK);
	suspend(1);
	os_print_color("\n                               `                  ", BROWN, BLACK);
	suspend(1);

}
