#include "../kernel.h"
#include "../init/api.h"

void plant() {
	os_print_color("dddddddmmmdddmmmmmNNN", GREEN, BLACK);
	suspend(1);
	os_print_color("hsyyh", RED, BLACK);
	suspend(1);
	os_print_color("ddmNNNNNNNmNNmNNNNNNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("ddddddmmmmmdddmmNNNNNd", GREEN, BLACK);
	suspend(1);
	os_print_color("ossyh", RED, BLACK);
	suspend(1);
	os_print_color("mNNNNNNNNmmmmmNNNmNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("dddddddmmmdddmmmmmNNN", GREEN, BLACK);
	suspend(1);
	os_print_color("hsyyh", RED, BLACK);
	suspend(1);
	os_print_color("ddmNNNNNNNmNNmNNNNNNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("ddddddmmmmmdddmmNNNNNd", GREEN, BLACK);
	suspend(1);
	os_print_color("ossyh", RED, BLACK);
	suspend(1);
	os_print_color("mNNNNNNNNmmmmmNNNmNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("dddddddmmmdddmmmmmNNN", GREEN, BLACK);
	suspend(1);
	os_print_color("hsyyh", RED, BLACK);
	suspend(1);
	os_print_color("ddmNNNNNNNmNNmNNNNNNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("ddddddmmmmmdddmmNNNNNd", GREEN, BLACK);
	suspend(1);
	os_print_color("ossyh", RED, BLACK);
	suspend(1);
	os_print_color("mNNNNNNNNmmmmmNNNmNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("dddddddmmmdddmmmmmNNN", GREEN, BLACK);
	suspend(1);
	os_print_color("hsyyh", RED, BLACK);
	suspend(1);
	os_print_color("ddmNNNNNNNmNNmNNNNNNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("ddddddmmmmmdddmmNNNNNd", GREEN, BLACK);
	suspend(1);
	os_print_color("ossyh", RED, BLACK);
	suspend(1);
	os_print_color("mNNNNNNNNmmmmmNNNmNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("dddddddmmmdddmmmmmNNN", GREEN, BLACK);
	suspend(1);
	os_print_color("hsyyh", RED, BLACK);
	suspend(1);
	os_print_color("ddmNNNNNNNmNNmNNNNNNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("ddddddmmmmmdddmmNNNNNd", GREEN, BLACK);
	suspend(1);
	os_print_color("ossyh", RED, BLACK);
	os_print_color("mNNNNNNNNmmmmmNNNmNNNNN\n", GREEN, BLACK);
	suspend(1);
	suspend(1);
	os_print_color("dddddddmmmdddmmmmmNNN", GREEN, BLACK);
	os_print_color("hsyyh", RED, BLACK);
	suspend(1);
	suspend(1);
	os_print_color("ddmNNNNNNNmNNmNNNNNNNNNN\n", GREEN, BLACK);
	os_print_color("ddddddmmmmmdddmmNNNNNd", GREEN, BLACK);
	suspend(1);
	os_print_color("ossyh", RED, BLACK);
	suspend(1);
	os_print_color("mNNNNNNNNmmmmmNNNmNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("dddddddmmmdddmmmmmNNN", GREEN, BLACK);
	suspend(1);
	os_print_color("hsyyh", RED, BLACK);
	suspend(1);
	os_print_color("ddmNNNNNNNmNNmNNNNNNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("ddddddmmmmmdddmmNNNNNd", GREEN, BLACK);
	suspend(1);
	os_print_color("ossyh", RED, BLACK);
	suspend(1);
	os_print_color("mNNNNNNNNmmmmmNNNmNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("dddddddmmmdddmmmmmNNN", GREEN, BLACK);
	suspend(1);
	os_print_color("hsyyh", RED, BLACK);
	suspend(1);
	os_print_color("ddmNNNNNNNmNNmNNNNNNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("ddddddmmmmmdddmmNNNNNd", GREEN, BLACK);
	suspend(1);
	os_print_color("ossyh", RED, BLACK);
	suspend(1);
	os_print_color("mNNNNNNNNmmmmmNNNmNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("ddddddmmmmmdddmmNNNNNd", GREEN, BLACK);
	suspend(1);
	os_print_color("hsyyh", RED, BLACK);
	suspend(1);
	os_print_color("ddmNNNNNNNmNNmNNNNNNNNNN\n", GREEN, BLACK);
	suspend(1);
	os_print_color("ddddddmmmmmdddmmNNNNNd", GREEN, BLACK);
	suspend(1);
	os_print_color("ossyh", RED, BLACK);
	suspend(1);
	os_print_color("mNNNNNNNNmmmmmNNNmNNNNN\n", GREEN, BLACK);
	suspend(1);
}
