#include "../kernel.h"
#include "../libc/atclib.h"

process art(){
	clscr();
	printf("                    AhnTri Sun\n\n");
	framebuffer_putstr("```````...................-.--.............```````", BROWN);
	suspend(1);
	framebuffer_putstr("\n`````...........--------------------..........````", BROWN);
	suspend(1);
	framebuffer_putstr("\n````.........--------------------------........```", BROWN);
	suspend(1);
	framebuffer_putstr("\n``........---------------", BROWN);
	suspend(1);
	framebuffer_putstr(":::::::::", YELLOW);
	suspend(1);
	framebuffer_putstr("-------........`", BROWN);
	suspend(1);
	framebuffer_putstr("\n`.......-------------", BROWN);
	suspend(1);
	framebuffer_putstr(":::::::::::::::", YELLOW);
	suspend(1);
	framebuffer_putstr("-----.........", BROWN);
	suspend(1);
	framebuffer_putstr("\n........---------", BROWN);
	suspend(1);
	framebuffer_putstr(":::::::::", YELLOW);
	suspend(1);
	framebuffer_putstr("//", YELLOW);
	suspend(1);
	framebuffer_putstr("::::::::::", YELLOW);
	suspend(1);
	framebuffer_putstr("-----.......", BROWN);
	suspend(1);
	framebuffer_putstr("\n......-------", BROWN);
	suspend(1);
	framebuffer_putstr("::::://///++++ooooooo++++///:::", YELLOW);
	suspend(1);
	framebuffer_putstr("---..", BROWN);
	suspend(1);
	framebuffer_putstr("\n.........-------", BROWN);
	suspend(1);
	framebuffer_putstr(":::////+++ooooooooooooo+++//:::", YELLOW);
	suspend(1);
	framebuffer_putstr("---", BROWN);
	suspend(1);
	framebuffer_putstr("\n......-------", BROWN);
	suspend(1);
	framebuffer_putstr("::::::////+++oooooo++///::", YELLOW);
	suspend(1);
	framebuffer_putstr("::----.....", BROWN);
	suspend(1);
	framebuffer_putstr("\n``........--------", BROWN);
	suspend(1);
	framebuffer_putstr("::::::////++++++++///:::", YELLOW);
	suspend(1);
	framebuffer_putstr("---.....", BROWN);
	suspend(1);
	framebuffer_putstr("\n```......--------", BROWN);
	suspend(1);
	framebuffer_putstr("::::::////", YELLOW);
	suspend(1);
	framebuffer_putstr("+++", RED);
	suspend(1);
	framebuffer_putstr("ooo", WHITE);
	suspend(1);
	framebuffer_putstr("++", RED);
	suspend(1);
	framebuffer_putstr("///:::", YELLOW);
	suspend(1);
	framebuffer_putstr("---......", BROWN);
	suspend(1);
	framebuffer_putstr("\n````......----------", BROWN);
	suspend(1);
	framebuffer_putstr("::://", YELLOW);
	suspend(1);
	framebuffer_putstr("++", RED);
	suspend(1);
	framebuffer_putstr("oooooooo", WHITE);
	suspend(1);
	framebuffer_putstr("++", RED);
	suspend(1);
	framebuffer_putstr("///:::", YELLOW);
	suspend(1);
	framebuffer_putstr("---....", BROWN);
	suspend(1);
	framebuffer_putstr("\n```````......--------", BROWN);
	suspend(1);
	framebuffer_putstr("::/", YELLOW);
	suspend(1);
	framebuffer_putstr("+", RED);
	suspend(1);
	framebuffer_putstr("ooossssssooo", WHITE);
	suspend(1);
	framebuffer_putstr("+", RED);
	suspend(1);
	framebuffer_putstr("/::", YELLOW);
	suspend(1);
	framebuffer_putstr("--......`", BROWN);
	suspend(1);
	framebuffer_putstr("\n   ````````....-------", BROWN);
	suspend(1);
	framebuffer_putstr("::/", YELLOW);
	suspend(1);
	framebuffer_putstr("+", RED);
	suspend(1);
	framebuffer_putstr("oosyyyyysso", WHITE);
	suspend(1);
	framebuffer_putstr("++", RED);
	suspend(1);
	framebuffer_putstr("/:", YELLOW);
	suspend(1);
	framebuffer_putstr("--......``", BROWN);
	suspend(1);
	framebuffer_putstr("\n   ````````....-------", BROWN);
	suspend(1);
	framebuffer_putstr("::/", YELLOW);
	suspend(1);
	framebuffer_putstr("+", RED);
	suspend(1);
	framebuffer_putstr("oosyyyyysso", WHITE);
	suspend(1);
	framebuffer_putstr("++", RED);
	suspend(1);
	framebuffer_putstr("/:", YELLOW);
	suspend(1);
	suspend(1);
	framebuffer_putstr("--......``", BROWN);
	suspend(1);
	framebuffer_putstr("\n     ````````...-------", BROWN);
	suspend(1);
	framebuffer_putstr(":/", YELLOW);
	suspend(1);
	framebuffer_putstr("++", RED);
	suspend(1);
	framebuffer_putstr("yhhhyyyys", WHITE);
	suspend(1);
	framebuffer_putstr("++", RED);
	suspend(1);
	framebuffer_putstr(":", YELLOW);
	suspend(1);
	framebuffer_putstr("--......```", BROWN);
	suspend(1);
	framebuffer_putstr("\n         ``````......---", BROWN);
	suspend(1);
	framebuffer_putstr("::/", YELLOW);
	suspend(1);
	framebuffer_putstr("+", RED);
	suspend(1);
	framebuffer_putstr("hhhyyy", WHITE);
	suspend(1);
	framebuffer_putstr("++", RED);
	suspend(1);
	framebuffer_putstr("/:", YELLOW);
	suspend(1);
	framebuffer_putstr(".......```", BROWN);
	suspend(1);
	framebuffer_putstr("\n         ``````......-----", BROWN);
	suspend(1);
	framebuffer_putstr(":/", YELLOW);
	suspend(1);
	framebuffer_putstr("++", RED);
	suspend(1);
	framebuffer_putstr("yyy", WHITE);
	suspend(1);
	framebuffer_putstr("++", RED);
	suspend(1);
	framebuffer_putstr("/:", YELLOW);
	suspend(1);
	framebuffer_putstr(".......```", BROWN);
	suspend(1);
	framebuffer_putstr("\n                 ````.......--", BROWN);
	suspend(1);
	framebuffer_putstr(":", YELLOW);
	suspend(1);
	framebuffer_putstr("---...``````       ", BROWN);
	framebuffer_putstr("\n                     ```````.....````             ", BROWN);
	suspend(1);
	framebuffer_putstr("\n                               `                  ", BROWN);
	suspend(1);

}
